---
- name: Install sanoid
  ansible.builtin.apt:
    package: ["sanoid"]
    update_cache: true
    state: present

- name: Create sanoid configuration directory
  ansible.builtin.file:
    path: /etc/sanoid
    owner: root
    group: root
    mode: "0755"
    state: directory

- name: Deploy sanoid configuration
  ansible.builtin.template:
    src: sanoid.conf.j2
    dest: /etc/sanoid/sanoid.conf
    owner: root
    group: root
    mode: "0644"

- name: Enable sanoid snapshot timer
  ansible.builtin.systemd:
    name: sanoid.timer
    enabled: true
    state: started

