---
leadpilot_version: ''

leadpilot_user: ubuntu
leadpilot_group: ubuntu
leadpilot_home: /home/ubuntu

uv_python_version: '3.14'

leadpilot_github_repo: 'https://github.com/kborovik/leadpilot'
leadpilot_github_token: ''

leadpilot_pipeline_limit: 50

leadpilot_cron_hour: '14'
leadpilot_cron_minute: '0'
