---
- name: Import GitHub CLI GPG Key
  ansible.builtin.apt_key:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    keyring: /etc/apt/trusted.gpg.d/github-cli.gpg
    state: present

- name: Add GitHub CLI Apt Repository
  ansible.builtin.apt_repository:
    filename: github-cli-packages
    repo: deb [arch=amd64] https://cli.github.com/packages stable main
    state: present

- name: Install GitHub CLI
  ansible.builtin.apt:
    package: [gh]
    update_cache: true
    state: present
