---
- name: Import Tailscale GPG Key
  ansible.builtin.apt_key:
    id: 2596A99EAAB33821893C0A79458CA832957F5868
    url: https://pkgs.tailscale.com/stable/ubuntu/noble.noarmor.gpg
    keyring: /etc/apt/trusted.gpg.d/tailscale.gpg
    state: present

- name: Add Tailscale Apt Repository
  ansible.builtin.apt_repository:
    filename: tailscale-packages
    repo: deb [arch=amd64] https://pkgs.tailscale.com/stable/ubuntu noble main
    state: present

- name: Install Tailscale Package
  ansible.builtin.apt:
    package: [tailscale]
    update_cache: true
    state: present

- name: Start Tailscale Service
  ansible.builtin.service:
    name: tailscaled
    state: started
    enabled: true

- name: Check Tailscale Status
  ansible.builtin.command:
    cmd: tailscale status --json
  register: tailscale_status
  changed_when: false
  failed_when: false

- name: Authenticate Tailscale
  ansible.builtin.command:
    cmd: tailscale up --auth-key={{ tailscale_auth_key }} --hostname={{ inventory_hostname }}
  register: tailscale_up
  changed_when: true
  when: tailscale_status.rc != 0 or (tailscale_status.stdout | from_json).BackendState != 'Running'
